exports.featuresMap = {
    'shorthand properties' : 'transform-es2015-shorthand-properties',
    'computed properties' : 'transform-es2015-computed-properties',
    'HTML-style comments' : null,
    'block-level function declaration' : 'transform-es2015-block-scoped-functions',
    'proper tail calls (tail call optimisation)' : null,
    'default function parameters' : 'transform-es2015-parameters',
    'rest parameters' : 'transform-es2015-parameters',
    'spread (...) operator' : 'transform-es2015-spread',
    'object literal extensions' : 'transform-es2015-literals',
    'for..of loops' : 'transform-es2015-for-of',
    'octal and binary literals' : null,
    'template strings' : 'transform-es2015-template-literals',
    'RegExp "y" and "u" flags' : [ 'transform-es2015-unicode-regex', 'transform-es2015-sticky-regex' ],
    'destructuring' : 'transform-es2015-destructuring',
    'Unicode code point escapes' : 'transform-es2015-unicode-regex',
    'new.target' : null,
    'const' : 'transform-es2015-constants',
    'let' : 'transform-es2015-block-scoping',
    'arrow functions' : 'transform-es2015-arrow-functions',
    'class' : 'transform-es2015-classes',
    'super' : 'transform-es2015-object-super',
    'generators' : 'transform-regenerator',
    'typed arrays' : null,
    'Map' : 'transform-regenerator',
    'Set' : 'transform-regenerator',
    'WeakMap' : 'transform-regenerator',
    'WeakSet' : 'transform-regenerator',
    'Proxy' : null,
    'Reflect' : null,
    'Promise' : null,
    'Symbol' : null, // 'transform-es2015-typeof-symbolnull' ?
    'well-known symbols' : null, // 'transform-es2015-typeof-symbolnull' ?
    'Object static methods' : null,
    'function "name" property' : 'transform-es2015-function-name',
    'String static methods' : null,
    'String.prototype methods' : null,
    'RegExp.prototype properties' : null,
    'Array static methods' : null,
    'Array.prototype methods' : null,
    'Number properties' : null,
    'Math methods' : null,
    'Array is subclassable' : null,
    'RegExp is subclassable' : null,
    'Function is subclassable' : null,
    'Promise is subclassable' : null,
    'miscellaneous subclassables' : null,
    'prototype of bound functions' : null,
    'Proxy, internal \'get\' calls' : null,
    'Proxy, internal \'set\' calls' : null,
    'Proxy, internal \'defineProperty\' calls' : null,
    'Proxy, internal \'deleteProperty\' calls' : null,
    'Proxy, internal \'getOwnPropertyDescriptor\' calls' : null,
    'Proxy, internal \'ownKeys\' calls' : null,
    'Object static methods accept primitives' : null,
    'own property order' : null,
    'miscellaneous' : null,
    'non-strict function semantics' : null,
    '__proto__ in object literals' : null,
    'Object.prototype.__proto__' : null,
    'String.prototype HTML methods' : null,
    'RegExp syntax extensions' : null
};